### ISSUE TITLE
Refactor MMRotate-1.x Documentation

### ISSUE THREAD

**Issue by zytx121** [open-mmlab/mmrotate#554]
MMRotate-1. x will be released soon, and we are building MMRotate-1.x documentation now, PRs from the community are welcome.
To make the community fully aware of the progress, we list the progress here.
Please feel free to leave a message and create a PR if you are willing to participate in any one of the documentation.

You can refer to [mmdet](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/docs) and [mmflow](https://github.com/open-mmlab/mmflow/tree/dev-1.x/docs).

# Phase 1 (English)

## Get Started
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/get_started.md @zytx121 
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/overview.md @zytx121 

## User Guides
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/config.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/dataset_prepare.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/inference.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/test_results_submission.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/train_test.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/useful_tools.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/user_guides/visualization.md

## Advanced Guides
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/conventions.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/customize_dataset.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/customize_losses.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/customize_models.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/customize_runtime.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/customize_transforms.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/advanced_guides/how_to.md
    - [ ] Use backbone network through MMClassification
    - [ ] Use MMDetection train DOTA dataset
    - [ ] Use MMRotate train MMOCR dataset

## Model Zoo
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/model_zoo.md @zytx121

## Notes
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/notes/faq.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/en/notes/projects.md

# Phase 2 (Chinese)

## Get Started
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/get_started.md @zytx121 
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/overview.md @zytx121 

## User Guides
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/config.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/dataset_prepare.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/inference.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/test_results_submission.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/train_test.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/useful_tools.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/user_guides/visualization.md

## Advanced Guides
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/conventions.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/customize_dataset.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/customize_losses.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/customize_models.md
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/customize_runtime.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/customize_transforms.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/advanced_guides/how_to.md
    - [ ] Use backbone network through MMClassification
    - [ ] Use MMDetection train DOTA dataset
    - [ ] Use MMRotate train MMOCR dataset

## Model Zoo
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/model_zoo.md @zytx121

## Notes
- [ ] [update] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/notes/faq.md
- [ ] [new] https://github.com/open-mmlab/mmrotate/blob/dev-1.x/docs/zh_cn/notes/projects.md
